### ISSUE TITLE
add support for gpg encrypted wiki file

### ISSUE THREAD

**Issue by QiangF** [abo-abo/plain-org-wiki#3]
Hello Sir,
Do you think finding file with org.gpg extension in the wiki directory a good idea? 
Thank you!

**Comment by abo-abo** [comment]
I haven't done anything with GPG so far. What's your workflow?

**Comment by QiangF** [comment]
I use org-wiki to keep notes and sync them using dropbox, so I can take notes on different computers. Some notes are encrypted and have extension like .org.gpg. Those notes are not shown in the helm completion list when I call plain-org-wiki (I bind it to C-0).  That's why I want you to add .gpg file extenstion to the find file filter list. 
Thank you!

**Comment by abo-abo** [comment]
OK, I understand now. Thanks.
