### ISSUE TITLE
pow-files-recursive uses deprecated function 

### ISSUE THREAD

**Issue by kiuuik** [abo-abo/plain-org-wiki#6]
On my machine your function [pow-files-recursive](https://github.com/abo-abo/plain-org-wiki/blob/master/plain-org-wiki.el#L58) sometimes fails. Then it complains it's missing the function ffip-project-files which is called in line 65 of plain-org-wiki.el.

I use melpa and have a recent version of find-file-in-project. There was a change in [November 2015](https://github.com/technomancy/find-file-in-project/commit/3b1f8ce53cd215a42cd437c9222e868706866d6f#diff-ec85380a928eaa1141f8824e4e47ce8aL305) in find-file-in-project: The function ffip-project-files was **renamed** to ffip-project-search. 

In the meantime the new function ffip-project-search seems to have changed, too. [Here](https://github.com/technomancy/find-file-in-project/blob/master/find-file-in-project.el#L546) is the new documenation. After reading this I changed your line 65 from ```(ffip-project-files)))))``` to ```(ffip-project-search "" nil)))))```. Since then I haven't encountered any error messages. But this might have been a pure coincidence.

Thanks again for your great software. I like plain-org-wiki a lot.

**Comment by abo-abo** [comment]
Thanks.
